### ISSUE TITLE
Package prefix

### ISSUE THREAD

**Issue by syohex** [kiwanami/emacs-github#2]
Package prefix `gh:` is similar to `gh.el` one.
I suppose it is better to use another prefix(`gh-issue-` etc).

https://github.com/sigma/gh.el

**Comment by kiwanami** [comment]
Thank you for your advice. 
`gh-issue-` is used at `gh-issues.el` in the gh.el project.
Is `ghi-` better?

**Comment by syohex** [comment]
I can't find project which use `ghi-` prefix but following project use `org-ghi` prefix.

https://github.com/punchagan/org-ghi

(I suppose using long name, like `ghi-vierwer`, is better for avoiding name collision
if you have no problem)

**Comment by kiwanami** [comment]
Thank you for your advice.
I would use `ghi-viewer`.
