### ISSUE TITLE
couldn't make it work

### ISSUE THREAD

**Issue by rhoit** [kiwanami/emacs-github#3]
I added the token as it said still couldn't make it work.
there is the output from message

```
REQUEST [error] Error from parser json-read: (void-function json-read)
REQUEST [error] Error (parse-error) while connecting to https://api.github.com/issues.
```

**Comment by kiwanami** [comment]
Hi, @rhoit 
Thank you for your report.
The problem is due to lack of requireing json library.
I fixed and pushed. Will you check it?

I'm sorry for my late response.
